apiVersion: v1
kind: Service
metadata:
  name: comment-svc
  namespace: eshop
spec:
  selector:
    app: comment
  type: ClusterIP
  ports:
    - name: comment-svc-http-port
      port: 8080
      targetPort: 8080

