apiVersion: v1
kind: Service
metadata:
  name: inventory-svc
  namespace: eshop
spec:
  selector:
    app: inventory
  type: ClusterIP
  ports:
    - name: inventory-svc-http-port
      port: 8080
      targetPort: 8080

